Project-Condor:
  org: Genezis
  project: 2
  inbox: Inbox
  labels:
    "W: In Progress": "В Прогрессе"
    "W: Discussion": "Design and Discussion"
    "W: Backlog": "Backlog"
    "W: Next": "Следующее"
