- type: job
  parent: CMJobSquadBase
  id: CMHospitalCorpsman
  name: cm-job-name-hospital-corpsman
  description: cm-job-description-hospital-corpsman
  playTimeTracker: CMJobHospitalCorpsman
  startingGear: CMGearHospitalCorpsman
  icon: "CMJobIconHospitalCorpsman"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - HospitalCorpsman

- type: startingGear
  id: CMGearHospitalCorpsman
  equipment:
    jumpsuit: CMJumpsuitMarineMedic # TODO RMC14 all squad roles should spawn with no jumpsuit but still have clothes on
    back: CMSatchelMarineMedic
    id: CMDogtagHospitalCorpsman

- type: startingGear
  id: CMGearHospitalCorpsmanEquipped
  equipment:
    jumpsuit: CMJumpsuitMarineMedic
    back: CMSatchelMarineMedic
    shoes: CMBootsBlackFilled
    gloves: CMHandsBlackMarine
    eyes: RMCGlassesMedicalHUDGlasses
    head: CMArmorHelmetM10Medic
    outerClothing: CMArmorM3Medium
    id: CMDogtagHospitalCorpsman
    ears: CMHeadsetAlphaMedic
    belt: CMBeltMedicBagFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointHospitalCorpsman
  name: hospital corpsman spawn point
  components:
  - type: SpawnPoint
    job_id: CMHospitalCorpsman
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: hospital_corpsman

- type: playTimeTracker
  id: CMJobHospitalCorpsman

