- type: job
  parent: CMJobSquadBase
  id: CMSquadLeader
  name: cm-job-name-squad-leader
  description: cm-job-description-squad-leader
  playTimeTracker: CMJobSquadLeader
  startingGear: CMGearSquadLeader
  icon: "CMJobIconSquadLeader"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-co
  accessGroups:
  - SquadLeader

- type: startingGear
  id: CMGearSquadLeader
  equipment:
    jumpsuit: JumpsuitMarine # TODO RMC14 all squad roles should spawn with no jumpsuit but still have clothes on
    back: CMSatchelMarine
    id: CMDogtagSquadLeader

- type: startingGear
  id: CMGearSquadLeaderEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: CMArmorHelmetM11
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagSquadLeader
    ears: CMHeadsetAlphaLeader

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSquadLeader
  name: squad leader spawn point
  components:
  - type: SpawnPoint
    job_id: CMSquadLeader
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: squad_leader

- type: playTimeTracker
  id: CMJobSquadLeader
