- type: job
  parent: CMJobSquadBase
  id: CMWeaponsSpecialist
  name: cm-job-name-weapons-specialist
  description: cm-job-description-weapons-specialist
  playTimeTracker: CMJobWeaponsSpecialist
  startingGear: CMGearWeaponsSpecialist
  icon: "CMJobIconWeaponsSpecialist"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - WeaponSpec

- type: startingGear
  id: CMGearWeaponsSpecialist
  equipment:
    jumpsuit: JumpsuitMarine # TODO RMC14 all squad roles should spawn with no jumpsuit but still have clothes on
    back: CMSatchelMarine
    id: CMDogtagWeaponsSpecialist

- type: startingGear
  id: CMGearWeaponsSpecialistEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagWeaponsSpecialist
    ears: CMHeadsetAlpha

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointWeaponsSpecialist
  name: weapons specialist spawn point
  components:
  - type: SpawnPoint
    job_id: CMWeaponsSpecialist
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: weapons_specialist

- type: playTimeTracker
  id: CMJobWeaponsSpecialist
