- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:SpeciesRequirement
      inverted: false
      species:
      - Vox
      - Diona
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15 hours
    - !type:AgeRequirement
      requiredAge: 20
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skills
        skills:
          RMCSkillCqc: 2
          RMCSkillConstruction: 2
          RMCSkillFirearms: 1
          RMCSkillFireman: 2
          RMCSkillEndurance: 2
          RMCSkillEngineer: 2
          RMCSkillExecution: 1
          RMCSkillIntel: 2
          RMCSkillJtac: 4
          RMCSkillLeadership: 3
          RMCSkillMedical: 3
          RMCSkillNavigations: 1
          RMCSkillOverwatch: 1
          RMCSkillPolice: 2
          RMCSkillPowerLoader: 2
          RMCSkillSmartGun: 1
          RMCSkillSurgery: 1
          RMCSkillVehicles: 1
      - type: MarineOrders

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter
