- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs # Corvax-RoleTime
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolster
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
    belt:
    - SpeedLoaderMagnum

# Weapon #Backmen
- type: loadout
  id: WeaponRevolverCMB
  equipment:
    belt: WeaponRevolverCMB

- type: loadout
  id: WeaponRevolverR44
  equipment:
    belt: WeaponRevolverR44

- type: loadout
  id: WeaponRevolverRebota
  equipment:
    belt: WeaponRevolverRebota

- type: loadout
  id: WeaponRevolverNY
  equipment:
    belt: WeaponRevolverNY

- type: loadout
  id: WeaponRevolverInspector
  equipment:
    belt: WeaponRevolverInspector

- type: loadout
  id: DetectiveCoatGrey
  equipment:
    outerClothing: ClothingOuterCoatDetectiveLoadoutGrey
