- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 10800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 # 30 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
    - !type:AgeRequirement
      requiredAge: 20
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skills
        skills:
          RMCSkillFirearms: 2
          RMCSkillJtac: 3
          RMCSkillSmartGun: 2
          RMCSkillCqc: 2
          RMCSkillConstruction: 2
          RMCSkillEndurance: 2
          RMCSkillEngineer: 2
          RMCSkillMeleeWeapons: 2
          RMCSkillSpecialistWeapons: 2
      - type: SquadArmorWearer
      - type: MarineOrders


- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: CMWeaponPistolMK80
  storage:
    back:
    - Flash
    - CMMagazinePistolMK80

# Pocket #Backmen

- type: loadout
  id: WeaponRevolverMatebaNew
  equipment:
    pocket1: WeaponRevolverMatebaNew

# Pocket 2 #Backmen

- type: loadout
  id: SpeedLoaderMagnum
  equipment:
    pocket2: SpeedLoaderMagnum
