- type: job
  parent: CMJobBase
  id: CMChiefEngineer
  name: cm-job-name-chief-engineer
  description: cm-job-description-chief-engineer
  playTimeTracker: CMJobChiefEngineer
  weight: 5
  startingGear: CMGearChiefEngineer
  icon: "CMJobIconChiefEngineer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-aso
  accessGroups:
  - CMCE
  hidden: true # TODO RMC14

- type: startingGear
  id: CMGearChiefEngineer
  equipment:
    jumpsuit: CMJumpsuitChiefEngineer
    back: CMSatchelMarineTech
    shoes: CMBootsBlack
    gloves: CMHandsInsulated
    id: CMIDCardChiefEngineer
    ears: CMHeadsetCE
    belt: CMBeltUtilityFilled
    pocket1: CMPouchElectronics

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointChiefEngineer
  name: chief engineer spawn point
  components:
  - type: SpawnPoint
    job_id: CMChiefEngineer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: chief_engineer

- type: playTimeTracker
  id: CMJobChiefEngineer
