- type: entity
  name: cleanades box
  parent: BoxCardboard
  id: BoxCleanerGrenades
  description: A box full of cleanades.
  components:
  - type: StorageFill
    contents:
      - id: CleanerGrenade
        amount: 4
  - type: Sprite
    layers:
      - state: box
      - state: flashbang

- type: entity
  name: набор "Химия это весело" от Триглава
  parent: BoxCardboard
  id: BoxAgrichem
  description: Для начинающего ботаника, готового узнать о том, как увеличить урожайность фермы.
  components:
  - type: StorageFill
    contents:
    - id: PaperAgrichemManual
    - id: ChemistryEmptyBottle01
    - id: PotassiumChemistryBottle
    - id: PhosphorusChemistryBottle
    - id: NitrogenChemistryBottle
    - id: HydrogenChemistryBottle
    - id: EthanolChemistryBottle
    - id: RadiumChemistryVial
    - id: ChlorineChemistryVial
  - type: Sprite
    layers:
      - state: boxwide
      - state: agrichemkit
