contact_links:
  - name: Предложение
    url: https://discord.com/channels/942051306577756200/1266113507418701915
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.com/channels/942051306577756200/1266113507418701915
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности в Discord.
