- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - MinerProfession #Genezis
  - SalvageSpecialist
  accountNumber: 1315 #backmen: currency

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Psychologist
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - ServiceWorker
  accountNumber: 1316 #backmen: currency

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - IAA # Corvax-IAA
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  accountNumber: 1317 #backmen: currency
  primary: false
  weight: 100
  lightColor: "#2c60f8" # SS220 Round End Titles

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant
  accountNumber: 1318 #backmen: currency

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Paramedic
  accountNumber: 1319 #backmen: currency

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Pilot # Corvax-Pilot
  - Detective
  - Warden
  - Brigmedic #backmen
  accountNumber: 1320  #backmen: currency

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Roboticist         #backmen: currency
  - Zookeeper
  - Scientist
  - ResearchAssistant
  accountNumber: 1321  #backmen: currency

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Prisoner #backmen
  - SAI #backmen
  - Pilot # Corvax-Pilot
  accountNumber: 1322  #backmen: currency
  primary: false
  roundEndTitlesHidden: true # SS220 Round End Titles
