- type: job
  parent: CMJobBase
  id: CMLiaison
  name: cm-job-name-liaison
  description: cm-job-description-liaison
  playTimeTracker: CMJobLiaison
  startingGear: CMGearLiaison
  icon: "CMJobIconLiaison"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-we-ya
  accessGroups:
  - MarineMain

- type: startingGear
  id: CMGearLiaison
  equipment:
    jumpsuit: CMJumpsuitLiaisonBlack
    back: CMSatchel
    shoes: CMShoesLaceup
    id: CMIDCardLiaison
    ears: CMHeadsetLeader

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointLiaison
  name: liaison spawn point
  components:
  - type: SpawnPoint
    job_id: CMLiaison
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: corp_liaison

- type: playTimeTracker
  id: CMJobLiaison
