- type: job
  parent: CMJobBase
  id: CMChiefMP
  name: cm-job-name-chief-mp
  description: cm-job-description-chief-mp
  playTimeTracker: CMJobChiefMP
  weight: 5
  startingGear: CMGearChiefMP
  icon: "CMJobIconChiefMP"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-co
  accessGroups:
  - CMP

- type: startingGear
  id: CMGearChiefMP
  equipment:
    jumpsuit: CMJumpsuitWO
    back: CMSatchelSecurity
    shoes: CMBootsBlackFilled
    head: CMHeadBeretWO
    eyes: CMGlassesSecurity
    gloves: CMHandsBlackMarine
    id: CMIDCardChiefMP
    outerClothing: CMArmorM3WO
    ears: CMHeadsetCMP
    belt: CMBeltSecurityFilled
    #    pocket1: TODO RMC14 tape recorder
    pocket2: CMPouchGeneralLarge

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointChiefMP
  name: chief mp spawn point
  components:
  - type: SpawnPoint
    job_id: CMChiefMP
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: chief_military_police

- type: playTimeTracker
  id: CMJobChiefMP
