# Blob
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBlob
  name: Blob Role
#  description: mind-role-blob-description
  components:
  - type: MindRole
    antagPrototype: Blob
    exclusiveAntag: true
  - type: BlobRole

# Flesh Cultists
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFlesh
  name: Flesh Cultist Role
#  description: mind-role-flesh-description
  components:
  - type: MindRole
    antagPrototype: FleshCultist
    exclusiveAntag: true
  - type: FleshCultistRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFleshLeader
  name: Flesh Cultist Leader Role
#  description: mind-role-flesh-description
  components:
  - type: MindRole
    antagPrototype: FleshCultistLeader
    exclusiveAntag: true
  - type: FleshCultistRole
    isLeader: true

# EvilTwin
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleEvilTwin
  name: Evil Twin Role
#  description: mind-role-evil-twin-description
  components:
  - type: MindRole
    antagPrototype: EvilTwin
    exclusiveAntag: true
  - type: EvilTwinRole

# Fugitive
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFugitive
  name: Fugitive Role
#  description: mind-role-fugitive-description
  components:
  - type: MindRole
    antagPrototype: Fugitive
    exclusiveAntag: true
  - type: FugitiveRole

# Bank
- type: entity
  parent: BaseMindRole
  id: MindRoleBankMemory
  name: Bank Memory
  #  description: mind-role-fugitive-description
  components:
  - type: MindRole
  - type: BankMemory
